### PR TITLE
3.1-137 update

### PR DESCRIPTION
**Pull request by cbrueffer**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by cbrueffer** [comment]
Thanks @bgruening ! A few more are ready for merge: https://github.com/conda-forge/r-sfsmisc-feedstock/pull/1 https://github.com/conda-forge/r-withr-feedstock/pull/4 https://github.com/conda-forge/r-stringi-feedstock/pull/9 https://github.com/conda-forge/r-assertthat-feedstock/pull/3

**Comment by bgruening** [comment]
Done! Thanks a bunch.

**Comment by bgruening** [comment]
@cbrueffer just one thing, we probably need to rebuild all of those again after this https://github.com/pulls?page=1&q=is%3Aopen+is%3Apr+archived%3Afalse+org%3Aconda-forge+-review%3Achanges_requested+-repo%3Aconda-forge%2Fstaged-recipes+author%3Aregro-cf-autotick-bot+Rebuild&utf8=%E2%9C%93 has reached r-base. At least the compiled r-packages.

**Comment by cbrueffer** [comment]
Good point; I'm mostly updating these so other R packages updates can go in. Then again, I could just restrict those to R <3.5 for now.

**Pull request merged**
